need mbedtls

url="https://github.com/nanomsg/nng/archive/refs/tags/v1.7.3.tar.gz"
hash="035f2c3cad4e45fc0d978c54a338c197d1937527ae6feb82180d428a96b83474"
file="nng.tar.gz"
src=$(fetch_untar "$url" "$file" "$hash")
cd $src

shared_defs="
-DNNG_STATIC_LIB
-DNNG_ELIDE_DEPRECATED
-DNNG_ENABLE_IPV6
-DNNG_SUPP_HTTP
-DNNG_SUPP_TLS
-DNNG_SUPP_WEBSOCKET
-DNNG_SUPP_SHA1
-DNNG_SUPP_BASE64
-DNNG_HAVE_STRNCASECMP=1
-DNNG_HAVE_STRNLEN=1
"

if [ "$TARGET_OS" = "macos" ]
then

  platformdir="posix"
  defs="
-DNNG_ENABLE_STATS
-DNNG_HAVE_BACKTRACE=1
-DNNG_HAVE_BUS0
-DNNG_HAVE_FLOCK=1
-DNNG_HAVE_GETPEEREID=1
-DNNG_HAVE_INET6=1
-DNNG_HAVE_KQUEUE=1
-DNNG_HAVE_LANGINFO=1
-DNNG_HAVE_LOCALPEERCRED=1
-DNNG_HAVE_LOCALPEERPID=1
-DNNG_HAVE_LOCKF=1
-DNNG_HAVE_MSG_CONTROL=1
-DNNG_HAVE_PAIR0
-DNNG_HAVE_PAIR1
-DNNG_HAVE_PTHREAD_ATFORK_PTHREAD=1
-DNNG_HAVE_PTHREAD_SETNAME_NP=1
-DNNG_HAVE_PUB0
-DNNG_HAVE_PULL0
-DNNG_HAVE_PUSH0
-DNNG_HAVE_REP0
-DNNG_HAVE_REQ0
-DNNG_HAVE_RESPONDENT0
-DNNG_HAVE_SEMAPHORE_PTHREAD=1
-DNNG_HAVE_SOCKETPAIR=1
-DNNG_HAVE_STDATOMIC=1
-DNNG_HAVE_STRCASECMP=1
-DNNG_HAVE_STRLCPY=1
-DNNG_HAVE_STRNCASECMP=1
-DNNG_HAVE_STRNLEN=1
-DNNG_HAVE_SUB0
-DNNG_HAVE_SURVEYOR0
-DNNG_HAVE_UNIX_SOCKETS=1
-DNNG_HIDDEN_VISIBILITY
-DNNG_MAX_EXPIRE_THREADS=8
-DNNG_MAX_POLLER_THREADS=8
-DNNG_MAX_TASKQ_THREADS=16
-DNNG_PLATFORM_DARWIN
-DNNG_PLATFORM_POSIX
-DNNG_PRIVATE
-DNNG_RESOLV_CONCURRENCY=4
-DNNG_TEST_LIB
-DNNG_TRANSPORT_FDC
-DNNG_TRANSPORT_INPROC
-DNNG_TRANSPORT_IPC
-DNNG_TRANSPORT_TCP
-DNNG_TRANSPORT_TLS
-DNNG_TLS_ENGINE_INIT=nng_tls_engine_init_mbed
-DNNG_TLS_ENGINE_FINI=nng_tls_engine_fini_mbed
-DNNG_TRANSPORT_WS
-DNNG_TRANSPORT_WSS
-D_GNU_SOURCE
-D_POSIX_PTHREAD_SEMANTICS
-D_REENTRANT
-D_THREAD_SAFE
"

elif [ "$TARGET_OS" = "linux" ]
then

  platformdir="posix"
  defs="
-DNNG_ENABLE_STATS
-DNNG_HAVE_GETRANDOM=1
-DNNG_HAVE_CLOCK_GETTIME=1
-DNNG_HAVE_BUS0
-DNNG_HAVE_FLOCK=1
-DNNG_HAVE_INET6=1
-DNNG_HAVE_EPOLL=1
-DNNG_HAVE_EVENTFD=1
-DNNG_USE_EVENTFD
-DNNG_HAVE_ABSTRACT_SOCKETS
-DNNG_HAVE_LANGINFO=1
-DNNG_HAVE_LOCALPEERPID=1
-DNNG_HAVE_LOCKF=1
-DNNG_HAVE_MSG_CONTROL=1
-DNNG_HAVE_PAIR0
-DNNG_HAVE_PAIR1
-DNNG_HAVE_PTHREAD_ATFORK_PTHREAD=1
-DNNG_HAVE_PTHREAD_SETNAME_NP=1
-DNNG_HAVE_PUB0
-DNNG_HAVE_PULL0
-DNNG_HAVE_PUSH0
-DNNG_HAVE_REP0
-DNNG_HAVE_REQ0
-DNNG_HAVE_RESPONDENT0
-DNNG_HAVE_SEMAPHORE_PTHREAD=1
-DNNG_HAVE_SOCKETPAIR=1
-DNNG_HAVE_STDATOMIC=1
-DNNG_HAVE_STRCASECMP=1
-DNNG_HAVE_STRLCPY=1
-DNNG_HAVE_STRNCASECMP=1
-DNNG_HAVE_STRNLEN=1
-DNNG_HAVE_SUB0
-DNNG_HAVE_SURVEYOR0
-DNNG_HAVE_UNIX_SOCKETS=1
-DNNG_HIDDEN_VISIBILITY
-DNNG_MAX_EXPIRE_THREADS=8
-DNNG_MAX_POLLER_THREADS=8
-DNNG_MAX_TASKQ_THREADS=16
-DNNG_PLATFORM_LINUX
-DNNG_PLATFORM_POSIX
-DNNG_PRIVATE
-DNNG_RESOLV_CONCURRENCY=4
-DNNG_TEST_LIB
-DNNG_TRANSPORT_FDC
-DNNG_TRANSPORT_INPROC
-DNNG_TRANSPORT_IPC
-DNNG_TRANSPORT_TCP
-DNNG_TRANSPORT_TLS
-DNNG_TLS_ENGINE_INIT=nng_tls_engine_init_mbed
-DNNG_TLS_ENGINE_FINI=nng_tls_engine_fini_mbed
-DNNG_TRANSPORT_WS
-DNNG_TRANSPORT_WSS
-D_GNU_SOURCE
-D_POSIX_PTHREAD_SEMANTICS
-D_REENTRANT
-D_THREAD_SAFE
"

elif [ "$TARGET_OS" = "windows" ]
then

  platformdir="windows"
  defs="
-DNNG_PLATFORM_WINDOWS
-DNNG_HAVE_CONDVAR
-DNNG_HAVE_SNPRINTF
-D_CRT_SECURE_NO_WARNINGS
-D_CRT_RAND_S
"
  #ldflags="-lws2_32 -lmswsock -ladvapi32"
fi

find src -type f -name '*_test.c' | xargs rm
rm -r src/sp/transport/zerotier

touch nng.c
zig build-lib -target $TARGET -O $OPT_ZIG \
  -I include \
  -I src \
  $defs \
  $shared_defs \
  $(pkg-config --cflags mbedtls) \
  nng.c \
  src/*.c \
  src/core/*.c \
  src/platform/$platformdir/*.c \
  $(find src/sp -type f -name '*.c') \
  $(find src/supplemental -type f -name '*.c') \
  -lc

cd "$BUILD_OUT"
mv "$src/include" .
mkdir lib
mv "$src/$(zigi lib nng)" lib
