#!/usr/bin/env sh
set -e

rewrite_flags() {
  transformed_args=""
  for arg in "$@"; do
      case "$arg" in
          -Wp,-MD,*)
              mfarg=$(echo "$arg" | sed 's/^-Wp,-MD,//')
              transformed_args="${transformed_args} -MD -MF ${mfarg}"
              ;;
          -Wl,--warn-common)
              ;;
          -Wl,--verbose)
              ;;
          -Wl,-Map,*)
              ;;
           *)
              transformed_args="${transformed_args} ${arg}"
      esac
  done
  echo "$transformed_args"
}

zig cc --target=$BB_BUILD_TARGET \
  -DBB_GLOBAL_CONST='' \
  -Wno-unused-command-line-argument \
  -Wno-ignored-optimization-argument \
  $(rewrite_flags "$@")
