#!/usr/bin/env sh

getgopath() {
  echo "$(dirname "$(dirname "$0")")"/golang/bin/go
}

gotools="$(dirname "$0")"
goi="$gotools/goi"
go=$(getgopath)

GOTMPDIR="$HOME/gotmp"
mkdir -p $GOTMPDIR

GOOS=${GOOS:-$($goi os)}
GOARCH=${GOARCH:-$($goi arch)}

exec env \
PATH="$gotools:$PATH" \
GOOS=$GOOS \
GOARCH=$GOARCH \
GOCACHE="$XDG_CACHE_HOME/go/cache" \
GOENV="/dev/null" \
GOMODCACHE="$XDG_CACHE_HOME/go/modcache" \
GOTMPDIR="$GOTMPDIR" \
GOTOOLCHAIN="local" \
CGO_ENABLED=1 \
AR="ar" \
CC="gocc" \
CXX="goc++" \
$go "$@"
