#!/usr/bin/env sh
# native compiler for rust

filtered_args=""
for arg in "$@"; do
  case $arg in
    "-Wl,-exported_symbols_list"*)
      ;;
    "-Wl,-dylib")
      ;;
    "-no-pie")
      ;;
    # crt ignores, since zig duplicates them
    *"/crti.o")
      ;;
    *"/crt1.o")
      ;;
    *"/rcrt1.o")
      ;;
    "-lgcc"|"-lgcc_s")
      ;;
    *)
      filtered_args="$filtered_args \"$arg\""
      ;;
  esac
done

eval "exec zig cc $filtered_args"
