#!/usr/bin/env sh
set -e

if [ "$TARGET_OS" = "macos" ]
then
  sdk="$BUILD_DEPS/macossdk/sdk"
  cflags="--sysroot=$sdk -I$sdk/usr/include -L$sdk/usr/lib -F$sdk/System/Library/Frameworks -DTARGET_OS_OSX=1"
elif [ "$TARGET_OS" = "ios" ]
then
  sdk="$BUILD_DEPS/iossdk/sdk"
  cflags="--sysroot=$sdk -I$sdk/usr/include -L$sdk/usr/lib -F$sdk/System/Library/Frameworks -DTARGET_OS_IOS=1 -Wno-availability -Wno-nullability-completeness -Wno-undef-prefix"
fi

filtered_args=""
for arg in "$@"; do
  case $arg in
    "--target="*)
      ;;
    "-Wl,-exported_symbols_list"*)
      ;;
    "-Wl,-dylib")
      ;;
    "-Wl,-Bdynamic")
      ;;
    "-Wl,-O1")
      ;;
    "-Wl,--disable-auto-image-base")
      ;;
    "-no-pie")
      ;;
    # crt ignores, since zig duplicates them
    *"/crti.o")
      ;;
    *"/crt1.o")
      ;;
    *"/rcrt1.o")
      ;;
    # gcc ignores
    "-lgcc"|"-lgcc_eh"|"-lgcc_s")
      ;;
    # windows ignores, for now
    "-lwinapi_"*)
      ;;
    "-lmsvcrt"|"-l:libpthread.a")
      ;;
    "-l"*".dll")
      arg="${arg%.dll}"
      filtered_args="$filtered_args \"$arg\""
      ;;
    *"/libcompiler_builtins-"*".rlib")
      # zig windows bug: https://github.com/ziglang/zig/issues/15107
      # lld-link: error: duplicate symbol: ___chkstk_ms
      # on windows
      # ar x libcompiler_builtins....
      # rm 135 (the one with chkstk ms)
      # ar rcs libcompiler_builtins.lib *.o
      filtered_args="$filtered_args \"$arg\""
      ;;
    *)
      filtered_args="$filtered_args \"$arg\""
      ;;
  esac
done

eval "exec zig cc -target $(rusti zigtarget) -O$OPT $filtered_args $cflags -lunwind"
