#!/usr/bin/env sh
set -e

XOS_PKG="$(realpath "$(dirname "$0")")"
xos_root="$(mktemp -d)"
tools="$xos_root/tools"
mkdir -p "$tools"
touch "$xos_root/.xos"
cp "$XOS_PKG"/* "$tools"

mktemp="$(which mktemp)"
cat <<EOF > "$tools/internal_mktemp"
#!/usr/bin/env sh
set -e
"$mktemp" \$@
EOF
chmod +x "$tools/internal_mktemp"

XOS_BOOTSTRAP=1 "$tools/build" xos
