#!/usr/bin/env sh
set -e

tools_dir=$1

[ -e $tools_dir/.ok ] && exit 0

mkdir -p $tools_dir

cat <<EOF > $tools_dir/system
#!/usr/bin/env sh
set -e
cmd=\$(PATH=$PATH which \$1)
shift
\$cmd \$@
EOF
chmod +x $tools_dir/system

cat <<EOF > $tools_dir/system_export
#!/usr/bin/env sh
set -e
export PATH="$PATH:\$PATH"
\$@
EOF
chmod +x $tools_dir/system_export

touch $tools_dir/.ok
