#!/bin/sh

set -e

src=$1
dst=$2
hash=$3


mkdir -p $(dirname $dst)
if [ ! -e $dst ]
then
  wget --no-check-certificate -q "$src" -O "$dst.tmp"
  mv "$dst.tmp" "$dst"
fi
hash_got="$(sha256sum $dst | cut -d ' ' -f1)"
if [ "$hash" != "$hash_got" ]
then
  echo "bad hash for $src"
  echo "expected $hash"
  echo "got $hash_got"
  exit 1
fi
