#!/usr/bin/env sh
set -e

pkg=$1
name=${2:-$pkg}

dst=$BUILD_DEPS/$name
if [ -d $dst ]
then
  echo "error in need: destination already exists. consider passing a name."
  echo "dst=$dst"
  exit 1
fi

pkgid=$(ARCH=$ARCH OPT=$OPT build $pkg)

mkdir -p $BUILD_DEPS
ln -s $BUILD_CACHE/$pkgid/out $dst
