#!/usr/bin/env sh
set -e

# Env:
# * XOS_BUILD_CACHE: stores download here
# * BUILD_DEPS: links download here

src=$1
name=$2
hash=$3

cache="$XOS_BUILD_CACHE/content"
hash_prefix=$(echo $hash | cut -c1-2)

dstdir="$cache/$hash_prefix/$hash"
dst="$dstdir/file"
if [ -e "$dst" ]
then
  mkdir -p "$BUILD_DEPS"
  ln -s "$dst" "$BUILD_DEPS/$name"
  exit 0
fi

tmpd="$(mktemp -d)"

wget --no-check-certificate -q "$src" -O "$tmpd/file"

hash_got="$(sha256sum "$tmpd/file" | cut -d ' ' -f1)"
if [ "$hash" != "$hash_got" ]
then
  hash_got_prefix=$(echo $hash_got | cut -c1-2)
  gotdir="$cache/$hash_got_prefix/$hash_got"
  mkdir -p "$gotdir"
  echo "$src" > "$gotdir/src"
  mv "$tmpd/file" "$gotdir"
  >&2 echo "bad hash for $src"
  >&2 echo "expected $hash"
  >&2 echo "got $hash_got"
  exit 1
fi

mkdir -p "$dstdir"
echo "$src" > "$dstdir/src"
mv "$tmpd/file" "$dst"

mkdir -p "$BUILD_DEPS"
ln -s "$dst" "$BUILD_DEPS/$name"
