#!/usr/bin/env sh
set -e

pkg=$1
name=$2

NEEDTARGET=${NEEDTARGET:-$TARGET}
NEEDOPT=${NEEDOPT:-$OPT}
NEEDDEPS=${NEEDDEPS:-$BUILD_DEPS}
NEEDTXT=${NEEDTXT:-dyndeps.txt}

if [ -z "$name" ] || [ "$name" = "--" ]
then
  name=$pkg
fi

dst=$NEEDDEPS/$name
if [ -d "$dst" ]
then
  >&2 echo "error in need: destination already exists. consider passing a name."
  >&2 echo "dst=$dst"
  exit 1
fi

# set $@ to build args, if any
shift
while [ "$#" -gt 0 ]
do
	if [ "$1" = "--" ]
	then
		shift
		break
	fi
	shift
done

# build
pkgid=$(TARGET=$NEEDTARGET OPT=$NEEDOPT xos_internal_build $pkg "$@")
pkgid_prefix=$(echo $pkgid | cut -c1-2)

# link
mkdir -p "$NEEDDEPS"
ln -s "$XOS_BUILD_CACHE/pkg/$pkgid_prefix/$pkgid/out" "$dst"

# log the dynamic dependency
argsquote() {
  [ $# = 0 ] && return
  printf " "
  while :
  do
    printf "'"
    printf %s "$1" | sed "s/'/'\\\\''/g"
    shift
    [ $# = 0 ] && break
    printf "' "
  done
  printf "'\n"
}
printf "$pkgid  $name  $pkg" >> "$XOS_BUILD_OUT/$NEEDTXT"
argsquote "$@" >> "$XOS_BUILD_OUT/$NEEDTXT"
printf "\n" >> "$XOS_BUILD_OUT/$NEEDTXT"
