#!/usr/bin/env sh
set -e

pkg=$1
name=${2:-$pkg}

while [ "$#" -gt 0 ]
do
	if [ "$1" = "--" ]
	then
		shift
		break
	fi
	shift
done

dst=$BUILD_DEPS/$name
if [ -d "$dst" ]
then
  >&2 echo "error in need: destination already exists. consider passing a name."
  >&2 echo "dst=$dst"
  exit 1
fi

pkgid=$(ARCH=$ARCH OPT=$OPT build $pkg "$@")

mkdir -p "$BUILD_DEPS"
ln -s "$BUILD_CACHE/$pkgid/out" "$dst"
