#!/usr/bin/env sh

depsdir=${PC_DEPS_DIR:-$BUILD_DEPS}
include_libs=0
include_cflags=0
pkg=""

pkg_config_default() {
  lib=$1
  mkdir -p "$BUILD_OUT/pkgconfig"
  cat <<EOF > $BUILD_OUT/pkgconfig/$lib.pc
Cflags: -I\${rootdir}/include
Libs: \${rootdir}/lib/$(zigi lib $lib)
EOF
}

while [ "$#" -gt 0 ]
do
  case "$1" in
  --libs)
    include_libs=1
    ;;
  --cflags)
    include_cflags=1
    ;;
  --gendefault)
    shift
    pkg_config_default $1
    exit 0
    ;;
  --*)
    >&2 echo "unrecognized flag $1"
    exit 1
    ;;
  *)
    pkg=$1
    ;;
  esac
  shift
done

lib=$(echo "$pkg/" | cut -d'/' -f2)
if [ -z "$lib" ]
then
  lib=$pkg
else
  pkg=$(echo "$pkg/" | cut -d'/' -f1)
fi

pc="$depsdir/$pkg/pkgconfig/$lib.pc"
if [ ! -f "$pc" ]
then
  >&2 echo "pkg-config: pc file does not exist at $pc"
  exit 1
fi

rootdir="$depsdir/$pkg"
while IFS= read -r line; do
  case $line in
    "Cflags:"*)
      if [ "$include_cflags" = 1 ]
      then
        eval "echo ${line#Cflags:}"
      fi
      ;;
    "Libs:"*)
      if [ "$include_libs" = 1 ]
      then
        eval "echo ${line#Libs:}"
      fi
      ;;
    *)
      # ignore
      ;;
  esac
done < "$pc"
