#!/usr/bin/env sh
set -e

pkg=$1

cd "$BUILD_PKG"
if [ -e "$BUILD_PKG/manifest.txt" ]
then
  srcfiles() {
    echo manifest.txt
    cat "$BUILD_PKG/manifest.txt"
  }
  srcfiles="$(srcfiles | sort)"
else
  srcfiles="$(find . -type f | cut -c3- | sort)"
fi
srcfiles_hash="$(sha256sum $srcfiles)"

echo "--- BEGIN XOS PKG ---"
echo "PKG=$pkg"
echo "ARGS=$ARGS"
echo "ARCH=$ARCH"
echo "OPT=$OPT"
echo "SRCS="
echo "$srcfiles_hash"
echo "DEPS=$DEPS"
echo "TOOLS=$TOOLDEPS"
echo "XOS=$XOS"
echo "--- END XOS PKG ---"
