#!/usr/bin/env sh
set -e

pkg=$1

cd "$BUILD_PKG"
if [ -e "$BUILD_PKG/manifest.txt" ]
then
  srcfiles() {
    echo manifest.txt
    cat "$BUILD_PKG/manifest.txt"
  }
  srcfiles="$(srcfiles | sort)"
else
  srcfiles="$(find . -type f | cut -c3- | sort)"
fi
srcfiles_hash="$(sha256sum $srcfiles)"

cat <<EOF
--- BEGIN XOS PKG ---
PKG=$pkg
ARGS=$ARGS
TARGET=$TARGET
OPT=$OPT
SRCS=
$srcfiles_hash
XOS=$XOS
--- END XOS PKG ---
EOF
