#!/usr/bin/env sh
set -e

tools_dir=$1

mkdir -p "$tools_dir"

cat <<EOF > "$tools_dir/system"
#!/usr/bin/env sh
set -e
cmd="\$(PATH=$PATH which \$1)"
shift
exec "\$cmd" "\$@"
EOF
chmod +x "$tools_dir/system"

cat <<EOF > "$tools_dir/system_export"
#!/usr/bin/env sh
export PATH="$PATH:\$PATH"
exec "\$@"
EOF
chmod +x "$tools_dir/system_export"

touch "$tools_dir/.ok"
