#!/usr/bin/env sh

set -e

case $1 in
  lib)
    lib=$2
    name="lib$lib".a
    [ "$TARGET_OS" = "windows" ] && name="$lib.lib"
    echo $name
    ;;
  dylib)
    lib=$2
    name="lib$lib".so
    [ "$TARGET_OS" = "windows" ] && name="$lib.lib"
    echo $name
    ;;
  exe)
    bin=$2
    name="$bin"
    [ "$TARGET_OS" = "windows" ] && name="$bin.exe"
    echo $name
    ;;
  libc)
    sdk=$2
    [ -z "$sdk" ] && exit 0
    sdkpath="$BUILD_DEPS/$sdk/sdk"
    sed "s|@@SDK@@|$sdkpath|g" "$BUILD_DEPS/$sdk/share/libc.txt" > libc-$sdk.txt
    echo "--libc $PWD/libc-$sdk.txt"
    ;;
  *)
    >&2 echo "unrecognized zig command"
    exit 1
    ;;
esac
